name: AnyItemArmour
version: '${project.version}'
main: me.lightningreflex.anyitemarmour.AnyItemArmour
authors: [ LightningReflex ]
description: A Minecraft plugin to equip any item as an armor piece.
