name: AnyItemArmour
version: '${project.version}'
main: me.lightningreflex.anyitemarmour.AnyItemArmour
api-version: 1.19
authors: [ LightningReflex ]
description: Minecraft plugin to equip any item as an armor piece.
website: https://discord.gg/C6RQMtXXcV
